-- DATABASE와 JAVA 연동 샘플

-- MEMBER2 테이블 생성하기
CREATE TABLE MEMBER2(
    NO          NUMBER,
    ID          VARCHAR2(20),
    NAME        VARCHAR2(20),
    PHONE       VARCHAR2(20),
    ADDR        VARCHAR2(50)
);

DESC MEMBER2;


-- MEMBER2 테이블의 NO를 생성하는 SEQUENCE 생성하기
CREATE SEQUENCE MEMBER2_NO
    INCREMENT BY 1;
    
DROP SEQUENCE MEMBER2_NO;
    
SELECT * FROM MEMBER2;

DELETE FROM MEMBER2;