-- MONSTER HUNTER WEAPONS DATABASE
-- DB id : monster_hunter
-- DB pw : tiger

-- 무기DB
CREATE TABLE WEAPONS(
    NAME            VARCHAR2(30)    CONSTRAINT WEAPONS_NAME_PK PRIMARY KEY,
    SORT            VARCHAR2(20)    NOT NULL,
    DAMAGE          NUMBER(4)       NOT NULL,
    CRITICAL        NUMBER(3)       DEFAULT 0,
    GRADE           NUMBER(2)       NOT NULL,
    ATTRIBUTE       VARCHAR2(10)    DEFAULT '무속성',
    ATTRIBUTE_VAL   NUMBER(3)       DEFAULT 0,
    SLOT_1          NUMBER(1)       DEFAULT 0   CONSTRAINT WEAPONS_SLOT_1_CH CHECK(SLOT_1 BETWEEN 0 AND 3),
    SLOT_2          NUMBER(1)       DEFAULT 0   CONSTRAINT WEAPONS_SLOT_2_CH CHECK(SLOT_2 BETWEEN 0 AND 3),
    SLOT_3          NUMBER(1)       DEFAULT 0   CONSTRAINT WEAPONS_SLOT_3_CH CHECK(SLOT_3 BETWEEN 0 AND 3),
    MATERIAL        VARCHAR(100)    NOT NULL,
    TREE            VARCHAR2(20)    NOT NULL,
    TREE_POSITION   NUMBER(2)       NOT NULL,
    SHARPNESS_1     NUMBER(2)       DEFAULT 0,  -- 적
    SHARPNESS_2     NUMBER(2)       DEFAULT 0,  -- 등
    SHARPNESS_3     NUMBER(2)       DEFAULT 0,  -- 노
    SHARPNESS_4     NUMBER(2)       DEFAULT 0,  -- 녹
    SHARPNESS_5     NUMBER(2)       DEFAULT 0,  -- 청
    SHARPNESS_6     NUMBER(2)       DEFAULT 0   -- 백
);

SELECT * FROM WEAPONS;

DESC WEAPONS;

DROP TABLE WEAPONS;

CREATE TABLE MH_TEST(
    NAME    VARCHAR2(20),
    NO      NUMBER(3)
);

SELECT * FROM MH_TEST;

-- 테스트 (지울것)
CREATE TABLE DEFAULT_TEST(
    SEX     CHAR(2)         DEFAULT '남'
    CONSTRAINT DEFAULT_TEST_SEX_CH CHECK(SEX IN('남', '여')),
    NAME    VARCHAR2(20)
);

CREATE TABLE DEFAULT_TABLE(
    NO      NUMBER(2),
    SEX     CHAR(2) DEFAULT '남'
    CONSTRAINT DEFAULT_TABLE_SEX_CH CHECK(SEX IN('남', '여'))
);

SELECT SEARCH_CONDITION FROM USER_CONSTRAINTS
WHERE CONSTRAINT_NAME = 'DEFAULT_TABLE_SEX_CH'
ORDER BY CONSTRAINT_NAME;