--
-- Project Bookstore

-- Member table
-- 회원 정보 테이블
CREATE TABLE MEMBER_INFO(
    MEM_ID         NUMBER(5) CONSTRAINT MEMBER_ID_PK PRIMARY KEY,
    MEM_NAME       VARCHAR2(10),
    MEM_TEL        VARCHAR2(11) CONSTRAINT MEMBER_TEL_U UNIQUE,
    MEM_EMAIL      VARCHAR2(20) CONSTRAINT MEMBER_EMAIL_U UNIQUE,
    MEM_RENT_NUM   NUMBER(5),
    MEM_PENALTY    DATE,
    CONSTRAINT MEMBER_RENT_FK FOREIGN KEY(MEM_RENT_NUM) REFERENCES RENTAL_INFO(RENTAL_NUMBER)
               ON DELETE SET NULL
);

DESC MEMBER_INFO;


-- Rental Table
-- 대여 정보 테이블
CREATE TABLE RENTAL_INFO(
    RENTAL_NUMBER           NUMBER(5) CONSTRAINT RENTAL_NUM_PK PRIMARY KEY,
    RENTAL_BOOK_NUMBER      NUMBER(5),
    RENTAL_BEGIN            DATE,
    RENTAL_RETURN           DATE
);

DESC RENTAL_INFO;


-- Book Table
-- 도서 정보 테이블
CREATE TABLE BOOK_INFO(
    BOOK_NUMBER         NUMBER(5) CONSTRAINT BOOK_NUM_PK PRIMARY KEY,
    BOOK_NAME           VARCHAR2(20) CONSTRAINT BOOK_NAME_NN NOT NULL,
    BOOK_AUTHOR         VARCHAR2(10),
    BOOK_PUBLISHER      VARCHAR2(10),
    BOOK_STATE          VARCHAR2(8) DEFAULT '대여가능'
);

DESC BOOK_INFO;